### ISSUE TITLE
data mismatch in SNAT

### ISSUE THREAD

**Issue by xxing9703** [stefanbroeer/JDFC_v1.1#1]
Hi,

When trying to run this code and reproduce the results, the following issue was identified. See attached.
SLC38 has 8 rows in the given spreadsheet of "rVmax.xlsx", one extra row than in the code (line 338-344, 7 rows are imported), as a consequence, LAT3 and LAT4 are misread (shifted by one line). 

![screenshot1](https://user-images.githubusercontent.com/16364863/144156143-e713bda6-d4d9-48c9-bf1e-1ef60ebbf0da.png)

Xi

**Comment by stefanbroeer** [comment]
Hello Xi,

Many thanks for letting me know. I noticed that something was wrong with LAT3. That probably explains it.
I will try to fix it.

Cheers
Stefan

Professor Stefan Broer
Research School of Biology (Bldg 134)
The Australian National University
Canberra ACT 2601 Australia
T: +61 2 6125 2540
M: ***@***.******@***.***>
W: Broer Group - Membrane transport and nutrition | ANU Research School of Biology<https://biology.anu.edu.au/research/groups/broer-group-membrane-transport-and-nutrition>

From: Xi Xing ***@***.***>
Sent: Wednesday, 1 December 2021 12:56 PM
To: stefanbroeer/JDFC_v1.1 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [stefanbroeer/JDFC_v1.1] data mismatch in SNAT (Issue #1)


Hi,

When trying to run this code and reproduce the results, the following issue was identified. See attached.
SLC38 has 8 rows in the given spreadsheet of "rVmax.xlsx", one extra row than in the code (line 338-344, 7 rows are imported), as a consequence, LAT3 and LAT4 are misread (shifted by one line).

[screenshot1]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F16364863%2F144156143-e713bda6-d4d9-48c9-bf1e-1ef60ebbf0da.png&data=04%7C01%7Cstefan.broeer%40anu.edu.au%7C9455dd6948ab49e1053108d9b46dcb5f%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637739205923640425%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ISmE53AgR9Lrq0fczdVJhxjJ39NwPpUzytzKzag7PXQ%3D&reserved=0>

Xi

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstefanbroeer%2FJDFC_v1.1%2Fissues%2F1&data=04%7C01%7Cstefan.broeer%40anu.edu.au%7C9455dd6948ab49e1053108d9b46dcb5f%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637739205923650362%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P%2FxI%2Fx5nT%2Bch1c0nomAdaID3gsWPfXlkLaaVKV47HIo%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADBHKTIOJP4WR7BRMJXKVYDUOV6EXANCNFSM5JDIWIAA&data=04%7C01%7Cstefan.broeer%40anu.edu.au%7C9455dd6948ab49e1053108d9b46dcb5f%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637739205923650362%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cXFGrXvgDGmBVyafVyuR4lIkoVYfEcLLJFdSwE%2Bn%2B00%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cstefan.broeer%40anu.edu.au%7C9455dd6948ab49e1053108d9b46dcb5f%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637739205923660323%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p%2FlPcacbokeojVmiQigysPh7Yv9Qhkv5eZSk0FDJ2gk%3D&reserved=0> or Android<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cstefan.broeer%40anu.edu.au%7C9455dd6948ab49e1053108d9b46dcb5f%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637739205923660323%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eZksjedlj9K26FE3iNtMLovHeUAP00EHHbqFzbSA8ho%3D&reserved=0>.

**Comment by xxing9703** [comment]
Hi Professor Broer,

Yes, LAT3 is the one that gets affected as it reads a blank line, while LAT4 reads LAT3, which happens to be the same values as LAT4, so is not affected.  I think, simply deleting a line (SNAT6) in rVmax.xlsx will fix.

Reading a blank line instead of numbers containing N/A actually causes errors here.  That's how this issue was found.  And also, rVmax, Kmex, Kmin, etc. are imported as cell arrays instead of double arrays, which also generates errors. I will have to do the data type conversion, e.g.,  rVmax=cellfun(@str2num, rVmax); in order to get through.   Not sure if the same errors show up or not? maybe due to different matlab versions?

Xi

**Comment by stefanbroeer** [comment]
Hello Xi,

Yes that works. The script works fine on Matlab 2019 but I had issues with 2020.
The student who wrote the script has left my group, makes it a bit harder for me to look after the script.

Cheers
Stefan

Professor Stefan Broer
Research School of Biology (Bldg 134)
The Australian National University
Canberra ACT 2601 Australia
T: +61 2 6125 2540
M: ***@***.******@***.***>
W: Broer Group - Membrane transport and nutrition | ANU Research School of Biology<https://biology.anu.edu.au/research/groups/broer-group-membrane-transport-and-nutrition>
